
import Head from "next/head";
import { NextPage } from "next";
import BasicLayout from "../../Layouts/BasicLayout";
import SwiperC from "../../components/Swiper";
import Browse from "../../components/Browse";


const Index = async () => {
    // const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}/top/anime`);
    // const anime = await response.json();
    // const data = anime.data;

  return (
      <BasicLayout home={true} pageName={"Websekai"} link={'/Home'} anak={        <div className="min-h-screen">
      <SwiperC />
        <div className="my-2 px-3">
            <div className="flex mb-3 justify-between text-green-500">
                <p>Top Hits Anime</p>
                <a href="#">See all..</a>
            </div>
            <Browse ayam={"ayam"} />
            {/* {data.map(data => {console.log(data.title)})} */}
            {/* {console.log(typeof data)} */}
        </div>
        <div className="px-3 pb-20">
            <div className="flex mb-3 justify-between text-green-500">
                <p>New Episode Releases</p>
                <a href="#">See all..</a>
            </div>
            <Browse />
        </div>
      </div>}>

      </BasicLayout>
  );
  return (
    <>
      <Head>
        <title>Websekai-Favourite</title>
        <meta name="description" content="Generated by Create Next Stack." />
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
      </Head>
      <BasicLayout
        home={true}
        pageName={'Home'}
        link={'/'}
      >
        <div>
          <SwiperC /></div>
      </BasicLayout>
    </>
  );
};

export default Index;